GEMINI_KEYS = ["AIzaSyApbgL9aaB7-lWhXAbUbtjkR-uB1YEA35A","AIzaSyA0-QL74-Y_cgqgBh76Sv7jk4BlX9R1hSU","AIzaSyBfzItvFwnXeE2GpFPtksVdiJdh68sT1IU","AIzaSyDYXhtIeeMpYXZJClGFl9Gl5Cyn7TSzvq8"]

# Add the PostgreSQL connection block
[connections.postgresql]
dialect = "postgresql"
host = "34.93.23.175"
port = "5432"
database = "postgres" # Or your specific Olist database name
username = "postgres" # Or your specific username
password = "Neuroscience@19"